Feature/react16
FlockOfBirds/badge-button pull request #3
Opened 2017-07-26 06:37 UTC by McDoyen

* Add react 16

2017-07-26 13:00 UTC, acellam requested changes

2017-07-26 13:00 UTC, mistaguy commented on src/components/Alert.ts
>          : null as any;
remove `as any`

2017-07-26 13:00 UTC, mistaguy commented on src/components/Alert.ts
>  const Alert: SFC<{ message?: string }> = ({ message }) =>
Make alert generic so that it can be used for different kind of alert like success, info, etc.

2017-07-26 13:00 UTC, mistaguy commented on src/components/Overlay.ts
> -import { DOM, SFC, SyntheticEvent } from "react";
There is already a transparent later from web modeler. Delete `Overlay.ts`. 
Please confirm this from the web modeler

2017-07-26 13:17 UTC, acellam requested changes

2017-07-26 13:17 UTC, mistaguy commented on README.md
> +![1](https://raw.githubusercontent.com/mendixlabs/badge-button/v1.1.1/assets/demo.png)
The `URL` has to be relative so that it can show in the mendix app store eg
![Demo](/assets/demo.png)

2017-07-26 13:17 UTC, mistaguy commented on README.md
The `URL` has to be relative so that it can show in the mendix app store

2017-07-27 14:15 UTC, McDoyen commented on src/components/Overlay.ts
> -import { DOM, SFC, SyntheticEvent } from "react";
Done

2017-07-27 14:22 UTC, McDoyen commented on src/components/Alert.ts
>  const Alert: SFC<{ message?: string }> = ({ message }) =>
Done

2017-07-27 14:22 UTC, McDoyen commented on src/components/Alert.ts
>          : null as any;
Done

2017-07-27 14:25 UTC, McDoyen commented on README.md
> +![1](https://raw.githubusercontent.com/mendixlabs/badge-button/v1.1.1/assets/demo.png)
Done

2017-07-27 14:26 UTC, McDoyen commented on README.md
Done

2017-07-28 08:11 UTC, Andries-Smit commented on README.md
> +![1](https://raw.githubusercontent.com/mendixlabs/badge-button/v1.1.1/assets/demo.png)
The `![1]` is the alt text, should actually put a sensible value into it. Describing the content of the image.

2017-07-31 14:20 UTC, closed without merging